/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as RecurringIndexRouteImport } from './routes/recurring.index'
import { Route as RecurringNewRouteImport } from './routes/recurring.new'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersNewRouteImport } from './routes/admin.customers.new'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsCategoryIdRouteImport } from './routes/admin.products.$categoryId'
import { Route as AdminReportsDistributionRouteImport } from './routes/admin.reports.distribution'
import { Route as AdminReportsProductionRouteImport } from './routes/admin.reports.production'
import { Route as RecurringRecurringIdIndexRouteImport } from './routes/recurring.$recurringId.index'
import { Route as RecurringRecurringIdEditRouteImport } from './routes/recurring.$recurringId.edit'
import { Route as AdminCustomersCustomerIdIndexRouteImport } from './routes/admin.customers.$customerId.index'
import { Route as AdminCustomersCustomerIdNewOrderRouteImport } from './routes/admin.customers.$customerId.new-order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringIndexRoute = RecurringIndexRouteImport.update({
  id: '/recurring/',
  path: '/recurring/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringNewRoute = RecurringNewRouteImport.update({
  id: '/recurring/new',
  path: '/recurring/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/admin/customers/new',
  path: '/admin/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsCategoryIdRoute = AdminProductsCategoryIdRouteImport.update({
  id: '/admin/products/$categoryId',
  path: '/admin/products/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsDistributionRoute =
  AdminReportsDistributionRouteImport.update({
    id: '/admin/reports/distribution',
    path: '/admin/reports/distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReportsProductionRoute = AdminReportsProductionRouteImport.update({
  id: '/admin/reports/production',
  path: '/admin/reports/production',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRecurringIdIndexRoute =
  RecurringRecurringIdIndexRouteImport.update({
    id: '/recurring/$recurringId/',
    path: '/recurring/$recurringId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecurringRecurringIdEditRoute =
  RecurringRecurringIdEditRouteImport.update({
    id: '/recurring/$recurringId/edit',
    path: '/recurring/$recurringId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomersCustomerIdIndexRoute =
  AdminCustomersCustomerIdIndexRouteImport.update({
    id: '/admin/customers/$customerId/',
    path: '/admin/customers/$customerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCustomersCustomerIdNewOrderRoute =
  AdminCustomersCustomerIdNewOrderRouteImport.update({
    id: '/admin/customers/$customerId/new-order',
    path: '/admin/customers/$customerId/new-order',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/summary': typeof SummaryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/recurring/new': typeof RecurringNewRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/recurring/': typeof RecurringIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$categoryId': typeof AdminProductsCategoryIdRoute
  '/admin/reports/distribution': typeof AdminReportsDistributionRoute
  '/admin/reports/production': typeof AdminReportsProductionRoute
  '/recurring/$recurringId/edit': typeof RecurringRecurringIdEditRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/recurring/$recurringId/': typeof RecurringRecurringIdIndexRoute
  '/admin/customers/$customerId/new-order': typeof AdminCustomersCustomerIdNewOrderRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/summary': typeof SummaryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/recurring/new': typeof RecurringNewRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/recurring': typeof RecurringIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$categoryId': typeof AdminProductsCategoryIdRoute
  '/admin/reports/distribution': typeof AdminReportsDistributionRoute
  '/admin/reports/production': typeof AdminReportsProductionRoute
  '/recurring/$recurringId/edit': typeof RecurringRecurringIdEditRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/recurring/$recurringId': typeof RecurringRecurringIdIndexRoute
  '/admin/customers/$customerId/new-order': typeof AdminCustomersCustomerIdNewOrderRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/design-system': typeof DesignSystemRoute
  '/summary': typeof SummaryRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/recurring/new': typeof RecurringNewRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/recurring/': typeof RecurringIndexRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/products/$categoryId': typeof AdminProductsCategoryIdRoute
  '/admin/reports/distribution': typeof AdminReportsDistributionRoute
  '/admin/reports/production': typeof AdminReportsProductionRoute
  '/recurring/$recurringId/edit': typeof RecurringRecurringIdEditRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/recurring/$recurringId/': typeof RecurringRecurringIdIndexRoute
  '/admin/customers/$customerId/new-order': typeof AdminCustomersCustomerIdNewOrderRoute
  '/admin/customers/$customerId/': typeof AdminCustomersCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/catalog'
    | '/contact'
    | '/design-system'
    | '/summary'
    | '/admin/documents'
    | '/orders/$orderId'
    | '/recurring/new'
    | '/admin/'
    | '/orders/'
    | '/recurring/'
    | '/admin/customers/new'
    | '/admin/orders/$orderId'
    | '/admin/products/$categoryId'
    | '/admin/reports/distribution'
    | '/admin/reports/production'
    | '/recurring/$recurringId/edit'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/recurring/$recurringId/'
    | '/admin/customers/$customerId/new-order'
    | '/admin/customers/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/catalog'
    | '/contact'
    | '/design-system'
    | '/summary'
    | '/admin/documents'
    | '/orders/$orderId'
    | '/recurring/new'
    | '/admin'
    | '/orders'
    | '/recurring'
    | '/admin/customers/new'
    | '/admin/orders/$orderId'
    | '/admin/products/$categoryId'
    | '/admin/reports/distribution'
    | '/admin/reports/production'
    | '/recurring/$recurringId/edit'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/recurring/$recurringId'
    | '/admin/customers/$customerId/new-order'
    | '/admin/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/catalog'
    | '/contact'
    | '/design-system'
    | '/summary'
    | '/admin/documents'
    | '/orders/$orderId'
    | '/recurring/new'
    | '/admin/'
    | '/orders/'
    | '/recurring/'
    | '/admin/customers/new'
    | '/admin/orders/$orderId'
    | '/admin/products/$categoryId'
    | '/admin/reports/distribution'
    | '/admin/reports/production'
    | '/recurring/$recurringId/edit'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/recurring/$recurringId/'
    | '/admin/customers/$customerId/new-order'
    | '/admin/customers/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  DesignSystemRoute: typeof DesignSystemRoute
  SummaryRoute: typeof SummaryRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  RecurringNewRoute: typeof RecurringNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RecurringIndexRoute: typeof RecurringIndexRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminProductsCategoryIdRoute: typeof AdminProductsCategoryIdRoute
  AdminReportsDistributionRoute: typeof AdminReportsDistributionRoute
  AdminReportsProductionRoute: typeof AdminReportsProductionRoute
  RecurringRecurringIdEditRoute: typeof RecurringRecurringIdEditRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  RecurringRecurringIdIndexRoute: typeof RecurringRecurringIdIndexRoute
  AdminCustomersCustomerIdNewOrderRoute: typeof AdminCustomersCustomerIdNewOrderRoute
  AdminCustomersCustomerIdIndexRoute: typeof AdminCustomersCustomerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring/': {
      id: '/recurring/'
      path: '/recurring'
      fullPath: '/recurring/'
      preLoaderRoute: typeof RecurringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring/new': {
      id: '/recurring/new'
      path: '/recurring/new'
      fullPath: '/recurring/new'
      preLoaderRoute: typeof RecurringNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/admin/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$categoryId': {
      id: '/admin/products/$categoryId'
      path: '/admin/products/$categoryId'
      fullPath: '/admin/products/$categoryId'
      preLoaderRoute: typeof AdminProductsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/distribution': {
      id: '/admin/reports/distribution'
      path: '/admin/reports/distribution'
      fullPath: '/admin/reports/distribution'
      preLoaderRoute: typeof AdminReportsDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/production': {
      id: '/admin/reports/production'
      path: '/admin/reports/production'
      fullPath: '/admin/reports/production'
      preLoaderRoute: typeof AdminReportsProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring/$recurringId/': {
      id: '/recurring/$recurringId/'
      path: '/recurring/$recurringId'
      fullPath: '/recurring/$recurringId/'
      preLoaderRoute: typeof RecurringRecurringIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring/$recurringId/edit': {
      id: '/recurring/$recurringId/edit'
      path: '/recurring/$recurringId/edit'
      fullPath: '/recurring/$recurringId/edit'
      preLoaderRoute: typeof RecurringRecurringIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId/': {
      id: '/admin/customers/$customerId/'
      path: '/admin/customers/$customerId'
      fullPath: '/admin/customers/$customerId/'
      preLoaderRoute: typeof AdminCustomersCustomerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId/new-order': {
      id: '/admin/customers/$customerId/new-order'
      path: '/admin/customers/$customerId/new-order'
      fullPath: '/admin/customers/$customerId/new-order'
      preLoaderRoute: typeof AdminCustomersCustomerIdNewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  DesignSystemRoute: DesignSystemRoute,
  SummaryRoute: SummaryRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  RecurringNewRoute: RecurringNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RecurringIndexRoute: RecurringIndexRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminProductsCategoryIdRoute: AdminProductsCategoryIdRoute,
  AdminReportsDistributionRoute: AdminReportsDistributionRoute,
  AdminReportsProductionRoute: AdminReportsProductionRoute,
  RecurringRecurringIdEditRoute: RecurringRecurringIdEditRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  RecurringRecurringIdIndexRoute: RecurringRecurringIdIndexRoute,
  AdminCustomersCustomerIdNewOrderRoute: AdminCustomersCustomerIdNewOrderRoute,
  AdminCustomersCustomerIdIndexRoute: AdminCustomersCustomerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
